import './css/container.css';
import './css/group-author.css';
import './css/group-contact.css';
import './css/group-default.css';
import './css/group-footer.css';
import './css/group-portfolio.css';
import './css/group-services.css';
import './css/group-testimonials.css';
import './css/group-title.css';
import './css/group-twitter.css';
import './css/header.css';
import './css/item-author.css';
import './css/item-default.css';
import './css/item-portfolio.css';
import './css/item-service.css';
import './css/logo.css';
import './css/navigation.css';
import './css/slogan.css';
import './css/style.css';
require.context("./", true, /^\.\/.*\.html/);
require.context("./img", true, /^\.\/.*\.png/);